# This file is part of the setup-specmatic.
#
# Copyright (c) 2023-2026 airSlate, Inc.
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      go-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: 'ci'
      include: 'scope'
    groups:
      actions:
        patterns:
          - '*'
