# This file is part of the setup-specmatic.
#
# Copyright (c) 2023 airSlate, Inc.
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

#
# Licensed configuration.
# For more see: https://github.com/github/licensed
#

sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd

reviewed:
  npm:
    - '@actions/http-client' # MIT
