name: Setup specmatic environment
description: Setup a specmatic environment and add it to the PATH.
author: airSlate, Inc.

inputs:
  specmatic-version:
    description: The specmatic version to download (if necessary) and use.
  check-latest:
    description: Set this option to true if you want the action to always check for the latest available version that satisfies the version spec.
    default: false
  token:
    description: Used to pull node distributions from setup-specmatic. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  specmatic-version:
    description: The installed specmatic version. Useful when given a version range as input.

runs:
  using: node16
  main: dist/index.js

branding:
  icon: check-square
  color: green
