# This file is part of the setup-specmatic.
#
# Copyright (c) 2023 airSlate, Inc.
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - 'feature/**'
      - 'releases/*'

jobs:
  build:
    name: Check Build & CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check install
        run: npm install

      - name: Run tests
        run: npm run all
